catalogs:
  build:
    '@commitlint/cli': ^20.3.1
    '@commitlint/config-conventional': ^20.3.1
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.13.0
    '@nuxt/kit': ^4.0.0
    '@pinia/nuxt': ^0.11.3
    '@vite-pwa/nuxt': ^1.1.0
    '@vueuse/nuxt': ^14.1.0
    nuxt: ^4.1.2
    unplugin: ^2.3.5
    vite: ^7.0.4
  dev:
    '@antfu/eslint-config': ^7.2.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    eslint-plugin-tailwindcss: 4.0.0-beta.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    tailwindcss: ^4.1.18
    typescript: ^5.9.3
    vue-tsc: ^3.2.4
  frontend:
    '@nuxt/ui': ^4.4.0
    '@nuxtjs/mdc': ^0.20.0
    '@vueuse/core': ^14.1.0
    openai: ^6.16.0
    pinia: ^3.0.4
    vue: ^3.5.27
    zod: ^4.3.6
  icons:
    '@iconify-json/carbon': ^1.2.18
    '@iconify-json/twemoji': ^1.2.5
  conflicts_build_h3_1_1:
    '@nuxt/devtools': ^3.1.1
  conflicts_build_h4_3_0:
    nuxt: ^4.3.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
